# Generated by Django 3.2.7 on 2021-12-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
