# Generated by Django 3.2.7 on 2021-12-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211217_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsubjects',
            options={'verbose_name_plural': 'Student Subjects'},
        ),
        migrations.RemoveField(
            model_name='studentsubjects',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentsubjects',
            name='subjects',
            field=models.ManyToManyField(to='student.Subject'),
        ),
        migrations.AddField(
            model_name='studentsubjects',
            name='term',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=1),
            preserve_default=False,
        ),
    ]
