# Generated by Django 3.2.7 on 2021-12-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubjects',
            name='subjects',
        ),
    ]
