# Generated by Django 3.2.7 on 2021-12-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentlevel_teacherlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='scientific_level',
            field=models.IntegerField(choices=[(1, 'Assistent'), (2, 'Senior Teacher'), (3, 'PhD'), (4, 'Professor')], default=1),
            preserve_default=False,
        ),
    ]
